animal = input("Enter animal: ")
animal2 = input("Enter another animal: ")
food1 = input("Enter a food: ")
drink = input("Enter a drink: ")
adjective = input("Enter an adjective: ")
adjective2 = input("Enter another adjective: ")

print("A", animal, "walked up to a " + drink + " stand")
print("And he said to the ", animal2, " running the stand")
print("Hey! (Bum bum bum) Got any ",food1)
print("The man said no, we just sell " + drink +"")
print("But it’s " + adjective + " and it's " + adjective2 + ", and it’s all home-made.")
print("Can I get you a glass?")
print("The " + animal + " said I’ll pass.")